# This workflow updates the repository for recent changes to llvm-project.
name: Integrate Monorepo Changes

on:
  # Run the workflow every day (9am PST) to pull in any changes from llvm-project.
  schedule:
    - cron:  '0 16 * * *'

  # Allows for running this workflow manually from the Actions tab.
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Timestamp Begin
        run: date

      - uses: actions/checkout@v4

      - name: Clone llvm-project
        uses: actions/checkout@v4
        with:
          repository: llvm/llvm-project
          ref: 'main'
          path: 'llvm_src'

      - name: Update extension source
        run: |
          cp -r llvm_src/llvm/utils/vim/* ./
          cp -r llvm_src/mlir/utils/vim/* ./
          cp llvm_src/LICENSE.TXT ./
          rm -f README

      - name: Commit updated source
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -- . ':!llvm_src/'
          git commit -m "Integrate from LLVM at llvm/llvm-project@$(git -C llvm_src rev-parse HEAD | head -1)" -a || echo "Extension source is already up-to-date"
          git push || 0

      - name: Timestamp End
        run: date
